### ISSUE TITLE
Insufficient privilege to add this mod for dev contributors

### ISSUE THREAD

**Issue by MNoya** [GetDotaStats/site#236] opened 2016-01-16 20:15 UTC
The contributors of the gamemode can also update it, so the mod request should also allow them to add statcollection.

**Comment by SinZ163** [comment] 2016-01-16 20:40
Duplicate of #141

**Comment by MNoya** [comment] 2016-01-16 20:45
Not a full duplicate, rather I would have one owner to be able to add stats to the mod. I know func_door will have the same problem that I'm having with FootmenFrenzy (not being the original uploader)

**Comment by SinZ163** [comment] 2016-01-16 20:47
Except the issue is that the normal webAPI for published file details doesn't contain contributors, only the owner.

**Comment by MNoya** [comment] 2016-01-16 20:50
I see. Given that and knowing mods still have to be approved manually by an admin who can check for contributors manually, I think it would be better to remove the restriction of being the owner of the gamemode to submit stats for it.

**Comment by jimmydorry** [comment] 2016-01-17 05:22
Agreed that members should be able to view everything an owner can. We can make it so the owner or admins can add and remove team members.

However, requesting a mod is a different kettle of fish. As sinz said, I don't see how we can facilitate it.

**Comment by MNoya** [comment] 2016-01-17 05:30
Can you check workshop submissions for a steamID? If so, you could check if the requested gamemode is on their list (contributors get the mod added to their submitted items)

**Comment by jimmydorry** [comment] 2016-01-17 05:49
I'm sure there's any number of hacks. Lemme finish the team thingy on my side.

**Comment by jimmydorry** [comment] 2016-01-17 08:52
I think the best solution is to allow admins to request a mod regardless of the owner. Admins have the power to add team members.

I don't see a nice way to facilitate this otherwise. Especially since steam pages can change when ever they feel like it, which would break the scraper.

**Comment by MNoya** [comment] 2016-01-17 13:15
What is the problem with anyone submitting a mod? I don't think there will be many (if any) cases of a non contributor bothering to submit it. And in the case of a false uploader, it still has to be accepted by an admin anyway. In the case of Admin-override, ' Login as the mod developer.' should change to a "Contact an Admin"

**Comment by jimmydorry** [comment] 2016-01-17 13:34
Allowing anyone to submit a mod won't change the fact that admin intervention is still required to put the submitter on the team.

Unless you are advocating for the submitter to be added as a team member, which we can do. It's ripe for abuse though, and has the potential to make a mess that's pretty hard to fix (signing up random mods and using their modID for unrelated mods).

For the few exceptional cases you can think of, we could just do a manual override, but I don't feel they should be representative of the usual.

**Comment by MNoya** [comment] 2016-01-17 13:37
Alright sounds good, lets go with Admin manual adding + "Contact and Admin" link on the "Insufficient privilege" message then.

**Comment by jimmydorry** [comment] 2016-01-17 13:38
Ok, sounds good.

**Closed** 2016-01-18 09:46 UTC
Labels: Admin, custom-games
